# Generated by Django 4.2.7 on 2024-06-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillFactuAPP', '0003_alter_usuario_contrasena'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='extension',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
